language: ruby
rvm:
  - 1.8.7
  - 1.9.3

script:
  - "rake lint"
  - "rake spec SPEC_OPTS='--format documentation'"
  
env:
  - PUPPET_VERSION=2.7.21
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.1

gemfile: .gemfile

notifications:
  email:
    - estermann.michel@gmail.com